### ISSUE TITLE
Multiplayer Demo (Placenote & ARKit Collaboration)

### ISSUE THREAD

**Issue by by-erinmichelle** [by-erinmichelle/master25-project-management#2]
- [x] follow tutorial and make sure it works
- [x] give each person a cube to represent phone position
- [x] create objects visible to both players
