### ISSUE TITLE
Spatial Audio Demo

### ISSUE THREAD

**Issue by by-erinmichelle** [by-erinmichelle/master25-project-management#3]
- [x] create record audio ui (priority 1)
- [x] record audio functionality (priority 1)
- [ ] attach audio to a game object
- [ ] create persistent game object
- [ ] play audio on collision with camera
