### ISSUE TITLE
Spatial Capture/Mapping Demo

### ISSUE THREAD

**Issue by by-erinmichelle** [by-erinmichelle/master25-project-management#4]
Look at what is possible with placenote, what are the limitations?
how large can the map be made? 
- [x] map the entire urbn lobby
- [x] lock content to a 3D object
- [x] get spatial capture toolkit to work
- [ ] 3D object regonition of medium object
- [ ] 3D object regonition of large object
- [ ] establish scale of unity objects to AR
- [ ] Try ARWorldTrackingConfiguration

**Comment by martinacalluori** [comment]
@by-erinmichelle
