### ISSUE TITLE
Combine Audio and Multiplayer Prototypes

### ISSUE THREAD

**Issue by by-erinmichelle** [by-erinmichelle/master25-project-management#53]
- [x] duplicate multiplayer collab scene
- [ ] add press and hold to record functionality from spatial audio demo
- [ ] instantiate game objects on release instead of hit
- [ ] certain color per player for instantiated game objects
- [ ] play audio on collision with device
- [x] basic ui to press and hold to record (text after start game)
- [x] remove localization/lost text
