### ISSUE TITLE
Thought Sharing Demo

### ISSUE THREAD

**Issue by by-erinmichelle** [by-erinmichelle/master25-project-management#63]
- [ ] room persistent
- [ ] map persistent (save id of map)
- [ ] test first with starting game object, with audio file attached
- [ ] test instantiating game object with audio file attached
- [ ] test instantiating game object w player recorded audio file

Dev tasks:
- [ ] record audio at central sculpture
- [ ] listen to recording at central sculpture
- [ ] record audio anywhere in urbn, save at central sculpture (for privacy)

Design tasks:
- [x] "working on" board experiment
- [ ] rough temporary sculpture
- [ ] come up with simplistic user flow
- [ ] rough wireframes of interface

**Comment by by-erinmichelle** [comment]
@by-erinmichelle
