### ISSUE TITLE
Guided Tour Demo

### ISSUE THREAD

**Issue by by-erinmichelle** [by-erinmichelle/master25-project-management#67]
- [x] scan prod hallway - done
- [x] localize map
- [ ] design story representation
- [x] audio plays on collision
- [x] lock story representations to localized map
- [x] get stories from prod seniors (goal: 20)
- [ ] priority 2: AR wayfinding
* experience starts in p.d. hallway
